### 1. 分页：获取用户信息 - GET请求
GET http://127.0.0.1:2222/api/user/page-mapper-obj
Accept: application/json

### 1. 分页：获取用户信息 - GET请求
GET http://127.0.0.1:2222/api/user/page-mapper-param
Accept: application/json

### 1. 分页：获取用户信息 - GET请求
GET http://127.0.0.1:2222/api/user/page-wrapper
Accept: application/json

### 1. 分页：获取用户信息 - GET请求
GET http://127.0.0.1:2222/api/user/page-lambda-wrapper
Accept: application/json

### 1. 分页：获取用户信息 - GET请求
GET http://127.0.0.1:2222/api/user/page-type-handler
Accept: application/json

### 1. 查询：获取用户信息 - GET请求
GET http://127.0.0.1:2222/api/user/infos?userId=1973975470661382146
Accept: application/json

### 1. 查询：获取用户信息 - GET请求
GET http://127.0.0.1:2222/api/user/info?userId=1973975470661382146
Accept: application/json

### 2. 保存用户 - POST请求
POST http://127.0.0.1:2222/api/user/save
Content-Type: application/json

{
  "name": "张三",
  "phoneNo": "13800138000",
  "gender": "男",
  "idNo": "110101199001011234"
}

### 3. 更新用户 - POST请求
POST http://127.0.0.1:2222/api/user/update
Content-Type: application/json

{
  "id": 1973975470661382146,
  "name": "魏贺生",
  "phoneNo": "13900139002",
  "gender": "男",
  "idNo": "110101199502022345"
}

### 4. 保存用户（错误示例）- POST请求
POST http://127.0.0.1:2222/api/user/save-error
Content-Type: application/json

{
  "name": "王五",
  "phoneNo": "13700137000",
  "gender": "男",
  "idNo": "110101199803033456"
}